export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Banner } from "./Banner";
export { default as Title } from "./Title";
export { default as Services } from "./Services";
export { default as FeaturedRooms } from "./FeaturedRooms";
export { default as Loading } from "./Loading";
export { default as Room } from "./Room";
export { default as StyledHero } from "./StyledHero";